name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          source-url: https://nuget.pkg.github.com/yurii-litvinov/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGETPAT}}
      - run: dotnet build 
      - run: dotnet test
