name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          source-url: https://nuget.pkg.github.com/yurii-litvinov/index.json
      - run: dotnet test
