name: Lint

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
      - run: dotnet new tool-manifest
      - run: dotnet tool install fantomas
      - run: dotnet fantomas --check . 
